export const GUILD_LIST = 'GUILD_LIST'
export const CHANNEL_LIST = 'CHANNEL_LIST'
export const MESSAGES_VIEW = 'MESSAGES_VIEW'
export const MESSAGE_INPUT = 'MESSAGE_INPUT'
export const USER_LIST = 'USER_LIST'
